/**
 * GENERATED by `xanots routes --emit`. Do not edit.
 *
 * Plain data plus one interpolator — this file imports nothing, so a frontend
 * gets the typed path/verb (and socket) contract without pulling the SDK runtime
 * into its bundle. Regenerate after changing an endpoint's name, verb, or api
 * group, or a realtime server's or channel's name.
 */

function fillParams(
  label: string,
  noun: string,
  template: string,
  params?: Record<string, string | number>,
  encode = false,
): string {
  const declared = [...template.matchAll(/\{([^/{}]+)\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        `${label}: \`${key}\` is not a {param} of this ${noun}.` +
          (declared.length ? ` Expected: ${declared.join(", ")}.` : ` This ${noun} is static.`),
      );
    }
  }
  return template.replace(/\{([^/{}]+)\}/g, (_all, key: string) => {
    const value = (params ?? {})[key];
    if (value === undefined || value === null || value === "") {
      throw new Error(`${label}: missing a value for the path param \`${key}\`.`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(`${label}: the path param \`${key}\` is ${value}.`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot contain "/" — ` +
          `it would address a different ${noun}.`,
      );
    }
    if (!encode) return text;
    // A "." or ".." segment is REMOVED before routing (and takes the segment
    // before it), and encoding does not help — the URL standard reads "%2e" as
    // a dot for that check too. Everything else rides percent-encoded.
    if (/^(\.|%2e){1,2}$/i.test(text)) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot be "${text}" — ` +
          `a "." or ".." segment addresses a different ${noun}.`,
      );
    }
    return encodeURIComponent(text);
  });
}

export const ROUTES = {
  "POST ask": { verb: "POST", path: "/api:gblagent/ask" },
  "GET queries": { verb: "GET", path: "/api:gblaudit/queries" },
  "POST login": { verb: "POST", path: "/api:gblauth/login" },
  "POST check-eligibility": { verb: "POST", path: "/api:gblbenefits/check-eligibility" },
  "GET get-coverage/{member_id}": { verb: "GET", path: "/api:gblbenefits/get-coverage/{member_id}" },
  "GET get-remaining-limit/{member_id}": { verb: "GET", path: "/api:gblbenefits/get-remaining-limit/{member_id}" },
  "GET get/{member_id}": { verb: "GET", path: "/api:gblmembers/get/{member_id}" },
  "POST run": { verb: "POST", path: "/api:gblseed/run" },
} as const;

/** Every endpoint in this workspace, keyed `"<VERB> <name>"` (e.g. `"GET listings"`). */
export type RouteName = keyof typeof ROUTES;

export function routePath(name: "POST ask"): string;
export function routePath(name: "GET queries"): string;
export function routePath(name: "POST login"): string;
export function routePath(name: "POST check-eligibility"): string;
export function routePath(name: "GET get-coverage/{member_id}", params: { "member_id": string | number }): string;
export function routePath(name: "GET get-remaining-limit/{member_id}", params: { "member_id": string | number }): string;
export function routePath(name: "GET get/{member_id}", params: { "member_id": string | number }): string;
export function routePath(name: "POST run"): string;

export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  // Read through a widened view: a workspace with no endpoints at all makes
  // `RouteName` `never`, which cannot index the literal type.
  const route = (ROUTES as Record<string, { verb: string; path: string } | undefined>)[name];
  if (!route) {
    throw new Error(
      `routePath: unknown route "${String(name)}". Routes are keyed "<VERB> <name>", ` +
        'e.g. "GET listings" — regenerate the manifest if the endpoint is new.',
    );
  }
  return fillParams(`routePath("${String(name)}")`, "route", route.path, params, true);
}
